---

- name: prerequisite
  yum: 
    name: curl
    state: present

- name: stop container
  shell: docker stop nginx
  ignore_errors: yes
  
- name: start container
  shell: docker run --rm --name nginx -d -p 80:80 nginx
  sudo: yes
  sudo_user: root


- name: test healthiness of the nginx container
  shell: curl -s -o /dev/null -I -w "%{http_code}" http://localhost
  register: health

- debug:
    var: health


- name: fetch default page of nginx
  shell: curl -s http://localhost
  register: default

- debug:
    var: default

- name: copy frequent.sh
  copy: 
    src: frequent.sh
    dest: /tmp/frequent.sh

- name: chown frequent.sh
  file:
    path: "/tmp/frequent.sh"
    owner: root
    group: root
    mode: 0500

- name: count most frequent words
  shell: /tmp/frequent.sh
  register: frequent
  sudo: yes
  sudo_user: root

- debug:
    var: frequent

- name: touch log file
  file:
    path: /tmp/nginx.log
    state: touch

- name: copy cron.sh
  copy: 
    src: cron.sh
    dest: /tmp/cron.sh

- name: chown cron.sh
  file:
    path: "/tmp/cron.sh"
    owner: root
    group: root
    mode: 0500

- cron:
    name: "resource log"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: "root"
    job: "/bin/sh /tmp/cron.sh"